//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoaHocOnl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        public int ID { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATED_AT { get; set; }
        public string STATUS_ARTICLE { get; set; }
        public string THUMBNAIL { get; set; }
        public string TYPE_ARTICLE { get; set; }
    
        public virtual USER_COURSE USER_COURSE { get; set; }
    }
}
