//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoaHocOnl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public string FEEDBACKID { get; set; }
        public int ID_USER { get; set; }
        public string ID_ORDER { get; set; }
        public System.DateTime DATE_FEEDBACK { get; set; }
        public string CONTENT_FEEDBACK { get; set; }
        public Nullable<int> RATE_FEEDBACK { get; set; }
    
        public virtual ORDER_COURSE ORDER_COURSE { get; set; }
    }
}
