//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoaHocOnl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_COURSEEntities : DbContext
    {
        public QL_COURSEEntities()
            : base("name=QL_COURSEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTICLE> ARTICLE { get; set; }
        public virtual DbSet<CART_OF_USER> CART_OF_USER { get; set; }
        public virtual DbSet<COMMENT_LESSON> COMMENT_LESSON { get; set; }
        public virtual DbSet<COURSE> COURSE { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACK { get; set; }
        public virtual DbSet<GRADES> GRADES { get; set; }
        public virtual DbSet<LESSON> LESSON { get; set; }
        public virtual DbSet<ORDER_COURSE> ORDER_COURSE { get; set; }
        public virtual DbSet<QUIZZES> QUIZZES { get; set; }
        public virtual DbSet<TEACHER> TEACHER { get; set; }
        public virtual DbSet<TYPE_COURSE> TYPE_COURSE { get; set; }
        public virtual DbSet<USER_COURSE> USER_COURSE { get; set; }
    }
}
