//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoaHocOnl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHER()
        {
            this.COURSEs = new HashSet<COURSE>();
        }
    
        public string ID_TEACHER { get; set; }
        public string NAME_TEACHER { get; set; }
        public string STATUS_TEACHER { get; set; }
        public string THUMBNAIL { get; set; }
        public System.DateTime D_CREATED { get; set; }
        public string LEVEL_TEACHER { get; set; }
        public string DESCRIPTION_TEACHER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE> COURSEs { get; set; }
    }
}
