//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhoaHocOnl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_COURSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_COURSE()
        {
            this.ARTICLE = new HashSet<ARTICLE>();
            this.CART_OF_USER = new HashSet<CART_OF_USER>();
            this.GRADES = new HashSet<GRADES>();
            this.ORDER_COURSE = new HashSet<ORDER_COURSE>();
        }
    
        public int ID_USER { get; set; }
        public string FULLNAME_USER { get; set; }
        public string PASSWORD { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<int> NUMBER_OF_COURSE { get; set; }
        public string EMAIL_USER { get; set; }
        public string PHONE_USER { get; set; }
        public string ROLE_USER { get; set; }
        public string STATUS_USER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTICLE> ARTICLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART_OF_USER> CART_OF_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADES> GRADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_COURSE> ORDER_COURSE { get; set; }
    }
}
